env:
  browser: true
  es2021: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:unicorn/recommended
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: {}
